repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v2.5.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: end-of-file-fixer
- repo: https://github.com/python/black
  rev: 19.3b0
  hooks:
    - id: black
      name: "Autoformat python files"
      types: [python]
      language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.8
  hooks:
    - id: flake8
      name: "Lint python files"
      types: [python]
      language_version: python3
      additional_dependencies: ['flake8-bugbear==19.3.0']
- repo: https://github.com/timothycrosley/isort
  rev: 4.3.21
  hooks:
    - id: isort
      name: "Sort python imports"
      types: [python]
      language_version: python3
