repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v3.4.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: end-of-file-fixer
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.3.0
  hooks:
    - id: check-github-workflows
- repo: https://github.com/python/black
  rev: 20.8b1
  hooks:
    - id: black
      name: "Autoformat python files"
      types: [python]
      language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.4
  hooks:
    - id: flake8
      name: "Lint python files"
      types: [python]
      language_version: python3
      additional_dependencies: ['flake8-bugbear==20.11.1']
- repo: https://github.com/timothycrosley/isort
  rev: 5.7.0
  hooks:
    - id: isort
      name: "Sort python imports"
      types: [python]
      language_version: python3
