repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.0.1
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: end-of-file-fixer
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.7.1
  hooks:
    - id: check-github-workflows
- repo: https://github.com/python/black
  rev: 21.11b1
  hooks:
    - id: black
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      additional_dependencies: ['flake8-bugbear==21.11.29']
- repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
  hooks:
    - id: isort
- repo: https://github.com/asottile/pyupgrade
  rev: v2.29.1
  hooks:
    - id: pyupgrade
      args: ["--py36-plus"]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910-1
  hooks:
    - id: mypy
      additional_dependencies:
        - types-setuptools
        - types-requests
        - click
        - 'globus-sdk==3.2.0'
- repo: local
  hooks:
    - id: fix-changelog
      name: "Fix changelog"
      entry: ./changelog.d/post-fix-changelog.py
      language: python
      files: ^changelog\.adoc$
