repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.0.1
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: end-of-file-fixer
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.4.1
  hooks:
    - id: check-github-workflows
- repo: https://github.com/python/black
  rev: 21.9b0
  hooks:
    - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
    - id: flake8
      additional_dependencies: ['flake8-bugbear==21.9.1']
- repo: https://github.com/timothycrosley/isort
  rev: 5.9.3
  hooks:
    - id: isort
- repo: https://github.com/asottile/pyupgrade
  rev: v2.26.0
  hooks:
    - id: pyupgrade
      args: ["--py36-plus"]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
    - id: mypy
      additional_dependencies:
        - types-setuptools
        - types-requests
        - 'globus-sdk==3.0.1'
