name: Publish Test PyPI Release

on:
  push:
    tags: ["*"]

jobs:
  build-dists:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: python -m pip install build

      - name: Set dev version prior to upload
        run: python ./scripts/set_dev_version.py

      - name: Build Dists
        run: python -m build .

      - uses: actions/upload-artifact@v3
        with:
          name: packages
          path: dist/*

  publish:
    needs: [build-dists]
    runs-on: ubuntu-latest
    environment: publish-test-pypi
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: packages
          path: dist

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
