name: build
on:
  push:
  pull_request:
  # build weekly at 4:00 AM UTC
  schedule:
    - cron: '0 4 * * 1'
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["2.7", "3.6", "3.7", "3.8"]
        # we do not want a large number of windows and macos builds, so
        # enumerate them explicitly
        include:
          - os: windows-latest
            python-version: 2.7
          - os: windows-latest
            python-version: 3.8
          - os: macos-latest
            python-version: 3.8
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }} "
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # without VC on windows, we can't install ruamel.yaml
      #
      # if you're reading this comment, I just want you to know that there is
      # no swearing here because I did all of my swearing out loud when we ran
      # into this issue
      - name: "Install Visual C++ for Python 2.7"
        if: ${{ matrix.os == 'windows-latest' && matrix.python-version == '2.7' }}
        run: choco install vcpython27 -f -y
      - name: Install Requirements
        run: python -m pip install -U pip setuptools tox
      - name: Run Linting
        # only lint on 3.8 for faster overall runs
        if: ${{ matrix.python-version == '3.8' }}
        run: python -m tox -e lint
      - name: Run Tests
        run: python -m tox -e py
